export const ModelNames = Object.freeze({
  USER: "User",
  USER_METADATA: "UserMetadata",
  JOB_SEEKER_PROFILE: "JobSeekerProfile",
  EMPLOYER_PROFILE: "EmployerProfile",
  JOB: "Job",
  JOB_ALERT: "JobAlert",
  SAVED_JOB: "SavedJob",
  APPLICATION: "Application",
  SUBSCRIPTION_PLAN: "SubscriptionPlan",
  SUBSCRIPTION: "Subscription",
  PAYMENT: "Payment",
  BLOG: "Blog",
  FAQ: "FAQ",
  STATIC_PAGE: "StaticPage",
  TESTIMONIAL: "Testimonial",
  CMS: "CMS",
  PARTNER: "Partner",
  EXPERIENCE: "Experience",
});
